packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  build:
    defu: ^6.1.4
    vue: ^3.5.17
  cli:
    '@antfu/eslint-config': ^4.16.2
    '@antfu/ni': ^24.1.0
    '@chatondearu/eslint-config': ^0.2.1
    bumpp: ^10.1.0
    eslint: ^9.22.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.5.0
    obuild: ^0.2.1
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    vite: ^6.2.1
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
